--\o /dev/null

DROP SCHEMA "IPYME_AUX" CASCADE;
CREATE SCHEMA "IPYME_AUX";



CREATE TABLE "IPYME_AUX"."LANGUAGE" (
    "MSG_ID" NUMERIC PRIMARY KEY
    , "LANG1" VARCHAR(255)
    , "LANG2" VARCHAR(255));

CREATE TABLE "IPYME_AUX"."COMPANY" (
    "C_ID" NUMERIC PRIMARY KEY
    , "C_NAME" VARCHAR(255)
    , "C_DATE" TIMESTAMP WITH TIME ZONE);

CREATE TABLE "IPYME_AUX"."TAX_TYPE" (
    "TT_ID" INT PRIMARY KEY,
    "TT_NAME" VARCHAR(255)
);

CREATE TABLE "IPYME_AUX"."CATEGORY" (
    "C_ID" NUMERIC PRIMARY KEY,
    "TT_NAME" VARCHAR(255)
);

CREATE TABLE "IPYME_AUX"."PRODUCT" (
    "P_ID" NUMERIC PRIMARY KEY,
    "P_CATEGORY" NUMERIC REFERENCES "IPYME_AUX"."CATEGORY",
    "P_DESCRIPTION" VARCHAR(255),
    "P_EXTENDED_DESCRIPTION" TEXT
);


CREATE TABLE "IPYME_AUX"."STORE_TYPE" (
    "ST_ID" NUMERIC PRIMARY KEY,
    "ST_NAME" VARCHAR(255)
);


CREATE TABLE "IPYME_AUX"."STORE" (
    "S_ID" NUMERIC PRIMARY KEY,
    "S_NAME" VARCHAR(255),
    "S_TYPE" NUMERIC REFERENCES "IPYME_AUX"."STORE_TYPE"
);

CREATE TABLE "IPYME_AUX"."ITEM" (
    "I_ID" NUMERIC PRIMARY KEY,
    "I_PRODUCT" NUMERIC REFERENCES "IPYME_AUX"."PRODUCT",
    "I_STORE" NUMERIC REFERENCES "IPYME_AUX"."STORE"
);


CREATE TABLE "IPYME_AUX"."ENTITY" (
    "E_ID" NUMERIC PRIMARY KEY,
    "E_PEOPLE" NUMERIC 
);


/*
CREATE TABLE "IPYME_AUX"."CUSTOMER" (
    "CU_ID" NUMERIC PRIMARY KEY,
    "CU_ENTITY" NUMERIC REFERENCES "IPYME_AUX"."ENTITY"
    "CU_TAX
);
*/


DROP SCHEMA "IPYME_FINAL" CASCADE;

ALTER SCHEMA "IPYME_AUX" RENAME TO "IPYME_FINAL";

\dn
